### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mirronake** [n-thumann/xbox-cloud-server-selector#8]
just writes error after xbox logo loading.

**Comment by n-thumann** [comment]
Can you elaborate on the issue you're experiencing (e.g. with logs and screenshots)?
I just tested my extension and couldn't identify any issues.

**Comment by mirronake** [comment]
![msedge_oMQCNWlvKn](https://github.com/n-thumann/xbox-cloud-server-selector/assets/96698262/e260b2a3-3550-45d6-b685-69bff11c50fe)

**Comment by n-thumann** [comment]
I just tried with region JapanEast and both IPv4 and IPv6 work fine for me 🤔

Can you to the following, please:
1. Open the browsers developer tools
2. Filter for `xbox-cloud-server-selector `
3. Reload the Xbox Cloud Gaming page
4. Start a game and wait for the error to appear
5. Expand the fields (click the little triangles) next to e.g. `Found regions:`

Can you post a screenshot of it? It should look something like:
![Screenshot 2023-09-03 at 20 33 23](https://github.com/n-thumann/xbox-cloud-server-selector/assets/46975855/7c59671a-7d5a-46f2-a9b6-48b8149157fe)

**Comment by n-thumann** [comment]
Any update on this? :)
